services:
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stocktracker
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  api:
    image: jakubolek/stocktracker-api:latest
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: stocktracker
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  app:
    image: jakubolek/stocktracker-app:latest
    container_name: app
    ports:
      - "80:3000"
    depends_on:
      - api
