version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stocktracker
    ports:
      - "5432:5432"

  backend:
    build: ../backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: stocktracker
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  # frontend:
  #   build: ../frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
