version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stocktracker
    ports:
      - "5432:5432"

  api:
    build: ../backend
    container_name: api
    ports:
      - "8080:8080"
      - "8000:8000" 
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: stocktracker
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  app:
    build: ../frontend
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - api
